// TokenType.java
public enum TokenType {
    CREAR, CALCULAR, TRANSFORMAR,
    CUADRADO, CIRCULO, RECTANGULO, TRIANGULO,
    AREA, PERIMETRO, ESCALAR, ROTAR,
    IDENTIFICADOR, NUMERO,
    PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO,
    COMA, PUNTO_Y_COMA, FIN
}
